src/ubtres/results/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, DateTimeField, IntegerField, BooleanField
from wtforms.validators import DataRequired


class ResultForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    build_date = DateTimeField('Build Date', validators=[DataRequired()])
    arch = StringField('Arch', validators=[DataRequired()])
    cpu = StringField('CPU', validators=[DataRequired()])
    soc = StringField('SoC', validators=[DataRequired()])
    toolchain = StringField('Toolchain', validators=[DataRequired()])
    basecommit = StringField('Base commit', validators=[DataRequired()])
    boardname = StringField('Boardname', validators=[DataRequired()])
    defconfig = StringField('Used default config', validators=[DataRequired()])
    images = StringField('Images', validators=[DataRequired()])
    success = BooleanField('success')

    content = TextAreaField('Content')
    submit = SubmitField('Post')

src/ubtres/main/routes.py
from flask import render_template, request, Blueprint
from ubtres.models import Result
from ubtres.utils import shorten_commit_id
from ubtres.utils import calc_basecommit

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    results = Result.query.order_by(Result.date_posted.desc()).paginate(page=page, per_page=15)
    for r in results.items:
        r = calc_basecommit(r)
    return render_template('home.html', results=results)

@main.route("/about")
def about():
    return render_template('about.html', title='About')

@main.route("/announcements")
def announcements():
    return render_template('announcements.html', title='Announcements')

src/ubtres/results/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint,
                   send_from_directory, current_app)
from flask_login import current_user, login_required
from ubtres import db
from ubtres.models import Result
from ubtres.results.forms import ResultForm
from ubtres.utils import stats_get_diff_sizes
import json

results = Blueprint('results', __name__)


@results.route("/result/new", methods=['GET', 'POST'])
@login_required
def new_result():
    form = ResultForm()
    if form.validate_on_submit():
        result = Result(title=form.title.data,
                build_date=form.build_date.data,
                arch=form.arch.data,
                cpu=form.cpu.data,
                soc=form.soc.data,
                toolchain=form.toolchain.data,
                basecommit=form.basecommit.data,
                boardname=form.boardname.data,
                defconfig=form.defconfig.data,
                images=form.images.data,
                content=form.content.data,
                author=current_user,
                success=form.success.data)
        db.session.add(result)
        db.session.commit()
        flash('Your new result is registered!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_result.html', title='New Result',
                           form=form, legend='New Result')


@results.route("/result/<int:result_id>")
def result(result_id):
    result = Result.query.get_or_404(result_id)

    result.json_images = json.loads(result.images)
    result.calc_values()
    if result.hassystemmap:
        values = stats_get_diff_sizes(result.defconfig, 1, uid=result.id)
        if values != None:
            return render_template('result.html', title=result.title, result=result, values=values[0])
        else:
            return render_template('result.html', title=result.title, result=result, values=None)
    return render_template('result.html', title=result.title, result=result, values=None)

@results.route("/result/files/results/<int:result_id>/<string:filename>")
def result_file(result_id, filename):
    return send_from_directory(current_app.config['STORE_FILES'] + f"/{result_id}",
                               filename, as_attachment=True)

src/ubtres/stats/routes.py
from flask import (make_response, flash, Blueprint, render_template)
from flask import current_app
from flask_login import current_user, login_required
from ubtres.utils import get_defconfig_data
from ubtres.utils import get_images_names
from ubtres.utils import convert_images_to_picture
from ubtres.utils import stats_get_diff_sizes
from ubtres.utils import shorten_commit_id
from ubtres import db
from ubtres.models import Result
from ubtres.errors.handlers import error_404, error_416
# pip3 install matplotlib --user
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
import io
import json

stats = Blueprint('stats', __name__)

def roundup(x):
    return x if x % 100 == 0 else x + 100 - x % 100

def rounddown(x):
    return x if x % 100 == 0 else x - 100 - x % 100

def side_values(num_list):
    mini = 10000000
    maxi = 0
    for n in num_list:
        if n < 0:
            continue
        if n > maxi:
            maxi = n
        if n < mini:
            mini = n
    return rounddown(mini), roundup(maxi)

def create_stats_image(values):
    # create the image
    fig = Figure(figsize=(14, len(values) * 7))
    row = 1
    for val in values:
        diffs = val["function"]
        axis = fig.add_subplot(len(values) * 2, 1, row)
        axis.set_title(f'sizediff in bytes between  {val["prevcommit"]} and {val["commit"]}')
        axis.set_xlabel("function")
        axis.set_ylabel("size in bytes")
        axis.grid(True)
        # get minimum and maximum
        xs = range(len(diffs))
        names = []
        deltap = []
        deltan = []
        for n in diffs:
            names.append(n["name"])
            if (n["delta"] >= 0):
                deltap.append(n["delta"])
            else:
                deltap.append(0)
            if (n["delta"] < 0):
                deltan.append(n["delta"])
            else:
                deltan.append(0)

        axis.set_xticks(xs)
        axis.set_xticklabels(names, rotation=90)
        axis.bar(names, deltap, width=0.5, color='r')
        axis.bar(names, deltan, width=0.5, color='b')
        row += 2

    canvas = FigureCanvas(fig)
    output = io.BytesIO()
    canvas.print_png(output)
    response = make_response(output.getvalue())
    response.mimetype = 'image/png'
    return response

@stats.route("/stats/<string:defconfig>/<string:imgtyp>/<int:count>")
def stats_defconfig(defconfig, imgtyp, count):
    if imgtyp == "diff_sizes":
        values = stats_get_diff_sizes(defconfig, count)
        if values == None:
            return error_416("diff_sizes")
        return create_stats_image(values)

    ids, dates, images = get_defconfig_data(defconfig, count)
    if dates == None:
        return error_404(0)

    images = convert_images_to_picture(images)
    img = None
    for n in images:
        if imgtyp == n["name"]:
            img = n
            break

    if img == None:
        return error_416(imgtyp)

    sz = img["values"]
    fig = Figure(figsize=(18, 18))
    axis = fig.add_subplot(1, 1, 1)
    axis.set_title(f'{img["name"]} size in bytes')
    minv, maxv = side_values(sz)
    axis.set_xlabel("Commit ID")
    axis.grid(True)
    # get minimum and maximum
    axis.set_ylim([minv, maxv])
    xs = range(count)
    axis.set_xticks(xs)
    axis.set_xticklabels(dates, rotation=45)
    axis.plot(xs, sz, 'r*', label=img["name"])
    axis.legend(bbox_to_anchor=(1.01, 1), loc='upper left', borderaxespad=0., shadow=True)
    canvas = FigureCanvas(fig)
    output = io.BytesIO()
    canvas.print_png(output)
    response = make_response(output.getvalue())
    response.mimetype = 'image/png'
    return response

@stats.route("/stats/<string:defconfig>/<int:count>")
def result_spl_uboot(defconfig, count):
    data = {"defconfig" : defconfig, "count" : str(count) }
    ids, dates, images = get_defconfig_data(defconfig, count)
    data["imagenames"] = get_images_names(images)
    return render_template('stats.html', title=f"Images for {defconfig}", data=data)

src/ubtres/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from ubtres import db, bcrypt
from ubtres.models import User, Result
from ubtres.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from ubtres.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if not current_user.isadmin:
        return redirect(url_for('main.home'))

    # why does this not work anymore ?
    #if current_user.is_authenticated:
    #    print("NO AUTH")
    #    return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password, about=form.about.data)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.about = form.about.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.about.data = current_user.about
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_results(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    results = Result.query.filter_by(author=user)\
        .order_by(Result.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_results.html', results=results, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

src/ubtres/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>U-Boot Testing about</h1>
{% endblock content %}

src/ubtres/templates/announcements.html
{% extends "layout.html" %}
{% block content %}
    <h1>Announcements</h1>
    <p> Use <a href=https://github.com/Rahix/tbot> Tbot </a></p>
    <p> <a href=https://tbot.tools>Documentation</a></p>
{% endblock content %}

src/ubtres/templates/home.html
{% extends "layout.html" %}
{% block content %}
        <result class="media content-section">
          <div class="media-body">

            <table class="table">
              <thead class=thead-dark>
                <tr>
                  <th scope="col">ID</th>
                  <th scope="col">user</th>
                  <th scope="col">Arch</th>
                  <th scope="col">cpu</th>
                  <th scope="col">SoC</th>
                  <th scope="col">Build Date</th>
                  <th scope="col">Basecommit</th>
                  <th scope="col">Boardname</th>
                  <th scope="col">defconfig</th>
                </tr>
              </thead>
              <tbody>
                {% for result in results.items %}
                  {% if result.success %}
                    <tr class="result-success">
                  {% else %}
                    <tr class="result-failure">
                  {% endif %}
                      <th scope="row"> <a href="{{ url_for('results.result', result_id=result.id) }}"> {{ result.id }}</a></th>
                      <td class="result-title"> <a href="{{ url_for('users.user_results', username=result.author.username) }}"> <img class="rounded-circle result-img" src="{{ url_for('static', filename='profile_pics/' + result.author.image_file) }}"> </a></img> </td>
                      <td class="result-title"> {{ result.arch }}</td>
                      <td class="result-title"> {{ result.cpu }}</td>
                      <td class="result-title"> {{ result.soc }}</td>
                      <td class="result-build_date"> {{ result.build_date }}</td>
		      <td class="result-basecommit"> <a href="https://gitlab.denx.de/u-boot/u-boot/-/commit/{{ result.basecommit_long }}">{{ result.basecommit_short }}</td>
                      <td class="result-boardname"> {{ result.boardname }}</td>
                      <td class="result-defconfig"><a href="https://gitlab.denx.de/u-boot/u-boot/-/blob/{{ result.basecommit_long }}/configs/{{ result.defconfig }}">{{ result.defconfig }}</td>
                    </tr>
                  {% endfor %}
              </tbody>
            </table>
          </div>
        </result>
    {% for page_num in results.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if results.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

src/ubtres/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>U-Boot test results - {{ title }}</title>
    {% else %}
        <title>U-Boot test results</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/ubtestresults/home">U-Boot test results</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                {% if current_user.isadmin %}
                  <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                  <a class="nav-item nav-link" href="{{ url_for('results.new_result') }}">Add new result</a>
                {% endif %}
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container-fluid">
      <div class="row">
        <div class="col-md-10">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-2">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>May we put some infos here?.
              <ul class="list-group">
                <a class="nav-item nav-link" href="{{ url_for('main.announcements') }}">Announcements</a>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
</body>
</html>

src/ubtres/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

src/ubtres/templates/result.html
{% extends "layout.html" %}
{% block content %}
  <result class="media content-section">
    <div class="result-metadata">
      <img class="rounded-circle result-img" src="{{ url_for('static', filename='profile_pics/' + result.author.image_file) }}">
      <br>
      <a class="result-user" href="{{ url_for('users.user_results', username=result.author.username) }}">{{ result.author.username }}</a>
    </div>
    <div class="media-body">
      <h2 class="result-title">{{ result.title }}</h2>
      <hr>
      {% if result.success %}
        <table class="table-success">
      {% else %}
        <table class="table-failure">
      {% endif %}
          <tr>
            <td class="table-td" >reported</td>
            <td class="table-td">{{ result.date_posted.strftime('%Y-%m-%d %H-%M-%S') }}</td>
          </tr>
          <tr>
            <td class="table-td">Build Date</td>
            <td class="table-td">{{ result.build_date }}</td>
          </tr>
          <tr>
            <td class="table-td">Architecture</td>
            <td class="table-td">{{ result.arch }}</td>
          </tr>
          <tr>
            <td class="table-td">CPU</td>
            <td class="table-td">{{ result.cpu }}</td>
          </tr>
          <tr>
            <td class="table-td">SoC</td>
            <td class="table-td">{{ result.soc }}</td>
          </tr>
          <tr>
            <td class="table-td">Toolchain</td>
            {% if result.toolchain_path  %}
              <td class="table-td"><a href="{{ result.toolchain_path }}">{{ result.toolchain }}</td>
            {% else %}
              <td class="table-td">{{ result.toolchain }}</td>
            {% endif %}
          </tr>
          <tr>
            <td class="table-td">Basecommit</td>
            <td class="table-td"> <a href="https://gitlab.denx.de/u-boot/u-boot/-/commit/{{ result.basecommit_long }}">{{ result.basecommit }}</td>
          </tr>
          <tr>
            <td class="table-td">Boardname</td>
            <td class="table-td">{{ result.boardname }}</td>
          </tr>
          <tr>
            <td class="table-td">Defconfig</td>
            <td class="table-td"><a href="https://gitlab.denx.de/u-boot/u-boot/-/blob/{{ result.basecommit_long }}/configs/{{ result.defconfig }}">{{ result.defconfig }}</td>
          </tr>
          {% if result.images %}
            {% for n in result.json_images %}
              <tr>
                <td class="table-td">{{ n["name"] }}</td>
                <td class="table-td">{{ n["size"] }} bytes = {{ n["sizekib"] }}</td>
              </tr>
            {%endfor%}
          {% endif %}
          {% if result.hastbotlog %}
            <tr>
              <td class="table-td">tbot log</td>
              <td class="table-td"><a href="files/results/{{result.id}}/tbot.log">tbot log</td>
            </tr>
          {% endif %}
          {% if result.hastbotjson %}
            <tr>
              <td class="table-td">tbot json log</td>
              <td class="table-td"><a href="files/results/{{result.id}}/tbot.json">tbot json</td>
            </tr>
          {% endif %}
          {% if result.hassystemmap %}
            <tr>
              <td class="table-td">System.map</td>
              <td class="table-td"><a href="files/results/{{result.id}}/System.map">System.map</td>
            </tr>
          {% endif %}
          <tr>
            <td class="table-td">Notes</td>
            <td class="table-td">{{ result.content }}</td>
          </tr>
          {% if result.hassystemmap %}
            {% if result.values != None %}
              <td class="table-td">Size diff to commit {{ values["prevcommit"] }}</td>
              <td class="table-td">

              {% if values["function"] %}
              {% if result.success %}
                <table class="table-success">
              {% else %}
                <table class="table-failure">
              {% endif %}
                <p>Function </p>
                <tr>
                  <th>Name</th>
                  <th>old size</th>
                  <th>new size</th>
                  <th>delta</th>
                </tr>

                {% for n in values["function"] %}
                <tr>
                  <td>{{ n["name"] }}</td>
                  <td>{{ n["oldsize"] }}</td>
                  <td>{{ n["newsize"] }}</td>
                  <td>{{ n["delta"] }}</td>
                </tr>
              {%endfor%}
              </table>
              {% endif %}

              {% if values["data"] %}
              {% if result.success %}
                <table class="table-success">
              {% else %}
                <table class="table-failure">
              {% endif %}
                <p>Data</p>
                <tr>
                  <th>Name</th>
                  <th>old size</th>
                  <th>new size</th>
                  <th>delta</th>
                </tr>

                {% for n in values["data"] %}
                <tr>
                  <td>{{ n["name"] }}</td>
                  <td>{{ n["oldsize"] }}</td>
                  <td>{{ n["newsize"] }}</td>
                  <td>{{ n["delta"] }}</td>
                </tr>
              {%endfor%}
              </table>
              {% endif %}

              {% if values["readonly"] %}
              {% if result.success %}
                <table class="table-success">
              {% else %}
                <table class="table-failure">
              {% endif %}
                <p>RO data</p>
                <tr>
                  <th>Name</th>
                  <th>old size</th>
                  <th>new size</th>
                  <th>delta</th>
                </tr>

                {% for n in values["readonly"] %}
                <tr>
                  <td>{{ n["name"] }}</td>
                  <td>{{ n["oldsize"] }}</td>
                  <td>{{ n["newsize"] }}</td>
                  <td>{{ n["delta"] }}</td>
                </tr>
              {%endfor%}
              </table>
              {% endif %}

              </td>
            {% endif %}
          {% endif %}
      </table>
    </div>
  </result>
{% endblock content %}

src/ubtres/templates/stats.html
{% extends "layout.html" %}
{% block content %}
  <result class="media content-section">
    <div class="media-body">
      {% for n in data["imagenames"] %}
        <img class="stats-img" src="/stats/{{ data["defconfig"] }}/{{ n }}/{{ data["count"] }}" alt="Image U-Boot">
      {%endfor%}
      <img class="stats-img" src="/stats/{{ data["defconfig"] }}/diff_sizes/{{ data["count"] }}" alt="diff sizes from System.map">
    </div>
  </result>
{% endblock content %}

src/ubtres/templates/user_results.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Testresults reported by {{ user.username }} ({{ results.total }})</h1>
    {% for result in results.items %}
        <result class="media content-section">
          <img class="rounded-circle result-img" src="{{ url_for('static', filename='profile_pics/' + result.author.image_file) }}">
          <div class="media-body">
            <div class="result-metadata">
              <a class="mr-2" href="{{ url_for('users.user_results', username=result.author.username) }}">{{ result.author.username }}</a>
              <small class="text-muted">reported {{ result.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <table class="table">
              <thead class=thead-dark>
                <tr>
                  <th scope="col">ID</th>
                  <th scope="col">user</th>
                  <th scope="col">title</th>
                  <th scope="col">Build Date</th>
                  <th scope="col">Basecommit</th>
                  <th scope="col">Boardname</th>
                  <th scope="col">defconfig</th>
                </tr>
              </thead>
              <tbody>
                {% if result.success %}
                  <tr class="result-success">
                {% else %}
                  <tr class="result-failure">
                {% endif %}
                    <th scope="row"> <a href="{{ url_for('results.result', result_id=result.id) }}"> {{ result.id }}</a></th>
                    <td class="result-title"> <a href="{{ url_for('users.user_results', username=result.author.username) }}"> <img class="rounded-circle result-img" src="{{ url_for('static', filename='profile_pics/' + result.author.image_file) }}"> </a></img> </td>
                    <td class="result-title"> {{ result.title }}</td>
                    <td class="result-build_date"> {{ result.build_date }}</td>
                    <td class="result-basecommit"> {{ result.basecommit }}</td>
                    <td class="result-boardname"> {{ result.boardname }}</td>
                    <td class="result-defconfig"> {{ result.defconfig }}</td>
                  </tr>
              </tbody>
            </table>


          </div>
        </result>
    {% endfor %}
    {% for page_num in results.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if results.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_results', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_results', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}